version: '3.8'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
    command: sh -c "npm install && npm run host"
